codecov:
  # Don't wait for all other statuses to pass before sending codecov status.
  require_ci_to_pass: no

comment:
  layout: " diff, flags, files"
  behavior: default # Update if exists, otherwise post new.
  require_changes: true  # only post the comment if coverage changes

# See https://docs.codecov.com/docs/commit-status
coverage:
  # Disable project and patch level coverage status check in favor of
  # individual component status checks.
  status:
    project: off
    patch: off

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        removed_code_behavior: fully_covered_patch
      - type: patch
        target: auto
        removed_code_behavior: fully_covered_patch

  individual_components:
    - component_id: maliput  # this is an identifier that should not be changed
      name: maliput  # this is a display name, and can be changed freely
      paths:
        - include/**
        - src/**

# Recommended by https://github.com/ros-tooling/action-ros-ci#integrate-action-ros-ci-with-codecov
fixes:
  - "ros_ws/src/*/maliput/::"
github_checks:
  # Disable GitHub line-by-line annotations.
  annotations: true

# Exclude unwanted directories from code coverage reports.
ignore:
  - "doc"
  - "test"
  - "tools"
