codecov:
  # Don't wait for all other statuses to pass before sending codecov status.
  require_ci_to_pass: no

comment:
  layout: " diff, flags, files"
  behavior: default # Update if exists, otherwise post new.
  require_changes: true  # only post the comment if coverage changes

# See https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project:
      default:
        target: auto
        removed_code_behavior: fully_covered_patch
    patch:
      default:
        target: auto
        removed_code_behavior: fully_covered_patch

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        removed_code_behavior: fully_covered_patch
      - type: patch
        target: auto
        removed_code_behavior: fully_covered_patch

  individual_components:
    - component_id: api  # this is an identifier that should not be changed
      name: api  # this is a display name, and can be changed freely
      paths:
        - include/maliput/api/**
        - src/api/**
    - component_id: base
      name: base
      paths:
        - include/maliput/base/**
        - src/base/**
    - component_id: common
      name: common
      paths:
        - include/maliput/common/**
        - src/common/**
    - component_id: geometry_base
      name: geometry_base
      paths:
        - include/maliput/geometry_base/**
        - src/geometry_base/**
    - component_id: math
      name: math
      paths:
        - include/maliput/math/**
        - src/math/**
    - component_id: plugin
      name: plugin
      paths:
        - include/maliput/plugin/**
        - src/plugin/**
    - component_id: routing
      name: routing
      paths:
        - include/maliput/routing/**
        - src/routing/**
    - component_id: test_utilities
      name: test_utilities
      paths:
        - include/maliput/test_utilities/**
        - src/test_utilities/**
    - component_id: utilities
      name: utilities
      paths:
        - include/maliput/utilities/**
        - src/utilities/**

# Recommended by https://github.com/ros-tooling/action-ros-ci#integrate-action-ros-ci-with-codecov
fixes:
  - "ros_ws/src/*/maliput/maliput/::"
github_checks:
  # Disable GitHub line-by-line annotations.
  annotations: true

# Exclude unwanted directories from code coverage reports.
ignore:
  - "doc"
  - "test"
  - "tools"
